import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../data/models/announcement_model.dart';
import '../../../data/models/material_model.dart';
import '../../../data/repositories/announcement_repository_impl.dart';
import '../../../data/repositories/material_repository_impl.dart';
import '../../../domain/repositories/announcement_repository.dart';
import '../../../domain/repositories/material_repository.dart';

final announcementRepoProvider = Provider<AnnouncementRepository>((_) => AnnouncementRepositoryImpl());
final materialRepoProvider = Provider<MaterialRepository>((_) => MaterialRepositoryImpl());

class HomeState {
  final List<AnnouncementModel> announcements;
  final List<MaterialModel> materials;
  final bool isLoading;
  final String? error;

  const HomeState({
    this.announcements = const [],
    this.materials = const [],
    this.isLoading = false,
    this.error,
  });

  HomeState copyWith({
    List<AnnouncementModel>? announcements,
    List<MaterialModel>? materials,
    bool? isLoading,
    String? error,
  }) => HomeState(
        announcements: announcements ?? this.announcements,
        materials: materials ?? this.materials,
        isLoading: isLoading ?? this.isLoading,
        error: error,
      );
}

class HomeNotifier extends StateNotifier<HomeState> {
  final AnnouncementRepository _announcementRepo;
  final MaterialRepository _materialRepo;
  final String _classroomId;

  HomeNotifier(this._announcementRepo, this._materialRepo, this._classroomId)
      : super(const HomeState(isLoading: true)) {
    _loadAll();
  }

  Future<void> _loadAll() async {
    state = state.copyWith(isLoading: true);
    try {
      // Assuming repositories will be updated to take classroomId
      final announcements = await _announcementRepo.getAnnouncements();
      final materials = await _materialRepo.getMaterials();
      
      // Filter here temporarily if repo isn't updated yet, but repo should handle it eventually.
      final filteredAnnouncements = announcements.where((a) => a.classroomId == _classroomId || a.classroomId == 'dummy_classroom_id').toList();
      final filteredMaterials = materials.where((m) => m.classroomId == _classroomId || m.classroomId == 'dummy_classroom_id').toList();

      state = state.copyWith(
        announcements: filteredAnnouncements,
        materials: filteredMaterials,
        isLoading: false,
      );
    } catch (e) {
      state = state.copyWith(isLoading: false, error: e.toString());
    }
  }

  Future<void> refresh() => _loadAll();

  Future<void> postAnnouncement({
    required String title,
    required String content,
    required String teacherId,
  }) async {
    final newAnnouncement = AnnouncementModel(
      id: '', // Should be generated by backend
      classroomId: _classroomId,
      title: title,
      content: content,
      createdBy: teacherId,
      createdAt: DateTime.now(),
    );
    await _announcementRepo.postAnnouncement(newAnnouncement);
    await _loadAll();
  }

  Future<void> uploadMaterial({
    required String title,
    required String fileUrl,
    required String teacherId,
  }) async {
    final newMaterial = MaterialModel(
      id: '',
      classroomId: _classroomId,
      title: title,
      fileUrl: fileUrl,
      uploadedBy: teacherId,
      createdAt: DateTime.now(),
    );
    await _materialRepo.uploadMaterial(newMaterial);
    await _loadAll();
  }
}

final homeProvider = StateNotifierProvider.family<HomeNotifier, HomeState, String>((ref, classroomId) {
  return HomeNotifier(
    ref.watch(announcementRepoProvider),
    ref.watch(materialRepoProvider),
    classroomId,
  );
});
